#  Dockerfile for Node Express Backend api (production)

FROM node:10.16-alpine

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Exports 
EXPOSE 8080

CMD ["npm","run","server"]
